"""change data type in column quantity

Revision ID: 44c4693b34c2
Revises: 6e408526c2ef
Create Date: 2024-10-27 11:59:05.442064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c4693b34c2'
down_revision = '6e408526c2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id_stock', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('in_out', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_stock')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    # ### end Alembic commands ###
